myString = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"
print(myString)
print(myString[2])
print(myString[2:5])#MARCAMOS INICIO Y FINAL
print(myString[:5]) #POR DEFECTO COGE DESDE EL INICIO DEL STRING
print(myString[2:]) #POR DEFECTO COGE HASTA EL FIN DEL STRING
print(myString[3:10:2]) #VA SALTANDO CADA 2 POSICIONES DESDE EL 3 HASTA EL 10
print(myString[::2]) #VA SALTANDO CADA 2 POSICIONES DESDE EL INICIO AL FINAL
print(myString[::-2]) #VA SALTANDO CADA 2 POSICIONES DESDE EL FINAL AL INICIO
print(myString[::-1]) #MUESTRA EL STRING AL REVES